### ISSUE TITLE
room.html?room=123  redirect to index.html

### ISSUE THREAD

**Issue by mkudev** [Krishnakumar59/CollegeMeet#4]
Hey there, 

The links to room always redirect to index.html, that is, if you send your room URL to another person, they cannot enter the room.

I have reviewed and trying to fix this but I would like to know if you could check it

Greetings

**Comment by Krishnakumar59** [comment]
it work in localhost or hosted online somewhere
simply another person only need your room no
just they have type his/her name and your room id
thats all

**Comment by Krishnakumar59** [comment]
or simply you can share my hosted link and tell other people the room no
OR you can host the code in cloud or something
then then able to join 

Or send this link 
https://main.d20he9cyumoef5.amplifyapp.com/

let me know if your issue is fixed or not

**Comment by Krishnakumar59** [comment]
YOU NEED TO HOST ON CLOUD
 AND SHARE THE LINK
